# Specify where tracks to play are stored
# !!! DO NOT CHANGE THE "/media/" PART IF INSERTING A USB DRIVE !!!
TRACKS_DIR: "/media/sherlock" # Replace "sherlock" with your $USERNAME

# Specify electronic components' pins on the RaspberryPi board
FW_PIN: 7 # Forward button - GPIO 4
BW_PIN: 11 # Backward button - GPIO 17
PLAY_PIN: 15 # Play/Pause button - GPIO 22
LAMP_PIN: 22 # LED light pin - GPIO 25
SWITCH_PIN: 33 # LED light on/off button - GPIO 13

# Specify other electronic and mediaplayer parameters
BOUNCE: 0.5 # [seconds]
SKIP_TIME: 10 # [seconds]
LONG_PRESS_TIME: 2 # [seconds]
CURRENT_IDX: 0
RESTART_TIME: 2 # [seconds]
SUPPORTED_FORMATS: ['mp3']