# Specify where tracks to play are stored
TRACKS_DIR: "/media/sherlock"

# Specify electronic components' pins on the RaspberryPi board
FW_PIN: 7 #4
BW_PIN: 11 #17
PLAY_PIN: 15 #22
LAMP_PIN: 22
SWITCH_PIN: 33

# Specify other electronic and mediaplayer parameters
BOUNCE: 0.5 # [seconds]
SKIP_TIME: 10 # [seconds]
LONG_PRESS_TIME: 2 # [seconds]
CURRENT_IDX: 0
RESTART_TIME: 2 # [seconds]
SUPPORTED_FORMATS: ['mp3']